//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStartProgram.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\TestService\\Debug1\\GI.exe")]
        public string ReadFile {
            get {
                return ((string)(this["ReadFile"]));
            }
            set {
                this["ReadFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\TestService\\Debug3\\WEB.ConsoleApp.exe")]
        public string ReadNotification {
            get {
                return ((string)(this["ReadNotification"]));
            }
            set {
                this["ReadNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GI")]
        public string ReadFileExeName {
            get {
                return ((string)(this["ReadFileExeName"]));
            }
            set {
                this["ReadFileExeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GI.COMPORT")]
        public string ReadComPortExeName {
            get {
                return ((string)(this["ReadComPortExeName"]));
            }
            set {
                this["ReadComPortExeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WEB.ConsoleApp")]
        public string ReadNotificationExeName {
            get {
                return ((string)(this["ReadNotificationExeName"]));
            }
            set {
                this["ReadNotificationExeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\TestService\\Debug2\\GI.COMPORT.exe")]
        public string ReadComPort {
            get {
                return ((string)(this["ReadComPort"]));
            }
            set {
                this["ReadComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string tmInerval {
            get {
                return ((string)(this["tmInerval"]));
            }
            set {
                this["tmInerval"] = value;
            }
        }
    }
}
